# This sample source code is offered only as an example of what can or might be built using the IICS Github APIs, 
# and is provided for educational purposes only. This source code is provided "as-is" 
# and without representations or warrantees of any kind, is not supported by Informatica.
# Users of this sample code in whole or in part or any extraction or derivative of it 
# assume all the risks attendant thereto, and Informatica disclaims any/all liabilities 
# arising from any such use to the fullest extent permitted by law.name: IDMC_DEPLOY_MAPPING_TASK


name: DEPLOY_MAPPING_TASK
# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      committed_sha:
        description: "Hash to deploy"
        type: string
        required: true

env:
  IICS_LOGIN_URL: https://dm-us.informaticacloud.com
  IICS_POD_URL: https://na1.dm-us.informaticacloud.com/saas
  
  IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
  IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}

  UAT_IICS_USERNAME: ${{ secrets.UAT_IICS_USERNAME }}
  UAT_IICS_PASSWORD: ${{ secrets.UAT_IICS_PASSWORD }}
  
  # Overriding until we connect the repository with a workflow_dispatch
  COMMIT_HASH: ${{ github.event.inputs.committed_sha }}

jobs:
  dev_build:
    name: Review Development Code
    environment:
      name: development
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout for safety,make sure MCTS included in commit wont go beyond 30MIN or expand this setting.

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install python modules
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Login to development
        run: python ./scripts/infa_login.py

      - name: Test Committed Mapping Tasks
        run: python ./scripts/infa_get_updates.py

  uat_commit:
    name: Complete uat promotion
    environment:
      name: uat
    needs: dev_build
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout for safety,make sure MCTS included in commit wont go beyond 30MIN or expand this setting.

    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install python modules
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set default username
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
                       
      - name: Checkout UAT Branch
        run: |
          git checkout uat
          git pull origin uat

      - name: Cherry-pick Commit from Dev
        run: |
          git cherry-pick -X theirs ${{ env.COMMIT_HASH }} || echo "Cherry-pick failed"

      - name: Push to UAT Branch
        run: |
          git status
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/masakinks2384/IDMC_SourceControl.git uat --force
